name: Bun Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: Run Tests
        run: bun install && bun test
